[package]
name = "wiew-eframe"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27.2", default-features = false, features = ["wgpu"] }
wiew = { version = "0.1.0", path = "../wiew" }
